language: csharp
mono: none
dotnet: 5.0.101
install: 
script:
- "./build.sh"
env:
  global:
    secure: PryCvsUrxO9LIWbvQScWny5FooBHrMULVWiiXjQqOC5InYke3hmktGhfIq/MQxA2xtJjKkQuv1fAk/3R4iweZS3l/UtDuwbqNVfxIysXrvvFPLGvms4n2rJPJIlmwG0JzkWDSCYyekl2YKDKAJ4znRR0AF453/WOzN50tO5KDweq3QLGxw5Xu8T7yNe+NQozjp8gZ6QuvHz7ecHDLXEV7d64TAPQfIGR2ORWCcK02gZLd5irk9SZCMEbqIGq9w8nOaWRwyO73IF9wXhLihnlWCGdW1ujWLorKO1hxv+iOcpwdPoEqVQKq8okGO7p3jYKiaFOMXjyMzEMbJ60CG65/QFcFE1x0sJ5O5zfpEzlTdHJ9D0kS76E4f3Ur3ZEZcR1skUatOmMgxPqOF8TTrOOlOgGjlzf+PhyL8EvKSlNcXy1fmY7UCOgsEQXjPUSDLFnn/Ihj71rAcbOTETKR30ARWRn9f2LTj/wFB3/upZJrh9g8FudoGOem8zxaqvKVZIlA/VArZNkpB2YlJq8rWUti5DGgssSbAzYTmfzncIEx5aLZJHR0wL6LnJ31WVulV74W2dsQF99OweB+Aq2g1asllLHED31pm8W5ChA8UP4ELGr4KbLsbJxBxC50BYpQz71bRkHUUrg0WEwqSqXobsujtz/RRp5zyfxwFgHyk3AGxE=
