language: csharp
dotnet: 5.0.101
install: 
script:
- "./build.sh"
env:
  global:
    secure: P8SlRKowmAqLzgpIm3xP80VFtLNX4oum6qcEmIcigF6+pVQivkCgAZNCMlURNrAsA4pHnV8FDcwMVcB4jb8dvHxG6ErjnZ5jvbpG5283ZVgYfFNVoqECp00pZxCdTuG9eF5G0Nc6W6k5Sz1+LFoCz2e3Qca/zglPMBgufnnAUS49bRk0PxVYWf+KL6XWqoVEQRnHk3MN9NTbVGya2lfzLkDIkWklA68N6qhCD7vV3ZrEQDAiwZZgZ5hIiTUWKJuiKro/M6yclcafsyJYX5KL/MYKwoWxdj3B/GuXf6EOTOxs6lrLmX/L2z/oEDNJv+lU/u5qxbumGhrTjS+owTlkZhnt3Nq6ZETm9rAXQzPAZr4zS4oNRLkPjmIVOzjkK33HkHSmKe5+9dAiuC1Ni+QcAzvTLAHE1+3uLSMQcAu9CH1nDiiTwzfM/Uf3wa1J2DdAcxkDWKgnOyJ/jdZ8pMRc6ApZOydtDDhbRvKhXeuCPRS3pGJHKEY+E1XzItgX6Sok22mKBOFUibqzondewVFOpgltpL7ulC/DT3ZPIRh3loXt3gdF4dFBgogoFoE5AQlj4ZUUBbtZ+laOvwdrgKaGbPaJMw3aqLUBGxx1uvyyAwJ5Fn+gUAei+aP7WOPSMSAlLCnFbOqj2D4IXXlrzo44CZGbpWpLzw+nbBBb1fgoqKM=
