version: 3.0.0.{build}
image: Visual Studio 2019

configuration: Release

build_script:
  - cmd: build.cmd

test: off

environment:
  FSHARP_AZURE_STORAGE_CONNECTION_STRING:
    secure: saFGdmViFU9yF3vNqonOY3deDHBkMvgI9OYOGP7Z3InBi8bu78K6Xthr6f7YEiL2VP2B/jN09WmGst38hNv9JQ3CNeDbpClWvJ5nFGAqoYAHpoAsauK6k+b+gKr2E/prVQTrISV0Q7ve0FJHtCDStYY+H6+XlWrUMtHPWnDmATB8c6rLWNb/P3ZEv0w/2dEIwjEtoYAKngKBW0dxsVzzmN9YO4LTfo9oUW1ayXiJdbLz0FT80gtm+JllUrW6pxuK7ElxrdUNLzDgs5g7Amx/+w==